import { ProfilePatch } from "@domain/profile/ProfilePatch.ts";
import type { PatchOperation } from "@domain/profile/ProfilePatch.ts";
import type { LearningProfileStore } from "@domain/profile/LearningProfileStore.ts";
import type { SessionEvent } from "@domain/session/SessionEvent.ts";
import type { Session } from "@domain/session/Session.ts";

/**
 * FinalizerService — owns the end-of-session delta pipeline (the "DeltaProcessor").
 * Owns: turning a finished session's event log into a `ProfilePatch` proposal
 * (BKT/FSRS/DSR evidence extraction summarized into `operations`), and atomically
 * committing that patch into the canonical store via compare-and-swap on `profileVersion`.
 * Does NOT own: session lifecycle (SessionService), prompt projection
 * (PromptProjectionService), or the store's own `applyPatch` mutation mechanics
 * (`LearningProfileStore.applyPatch` — the CAS here is the orchestration layer above it).
 * Per the Three Laws of the Tutor Engine: the profile is updated only here, only at session end.
 */

/** Keywords that indicate the assistant confirmed a student's answer as correct. */
const CORRECT_CONFIRMATION_KEYWORDS = [
	"correct",
	"right",
	"exactly",
	"well done",
	"great job",
	"that's it",
	"yes, that",
	"perfect",
] as const;

/**
 * Mastery delta scale factor: maps the success ratio offset from 0.5 to a ±mastery change.
 * A session where all answers were correct (ratio 1.0) yields a +0.10 delta.
 * A session where all answers were wrong (ratio 0.0) yields a -0.10 delta.
 */
const MASTERY_DELTA_SCALE_FACTOR = 0.20;

/** Minimum absolute mastery delta required before generating an update_mastery operation. */
const MINIMUM_MASTERY_DELTA_THRESHOLD = 0.005;

/** Default confidence value assigned to patch operations generated by the finalizer. */
const FINALIZER_OPERATION_CONFIDENCE = 0.70;

/** Maximum number of event IDs to include in evidenceRefs per operation (keeps patches compact). */
const MAX_EVIDENCE_REFS_PER_OPERATION = 5;

export class FinalizerService {
	/**
	 * Reduce a session's event log into a `ProfilePatch` proposal: derive mastery deltas
	 * (BKT), retrievability/scheduling updates (FSRS), and scaffolding/feedback-loop
	 * evidence (DSR) into `operations`, summarized with `evidenceRefs` back to source events.
	 */
	public async finalizeSessionToPatch(
		session: Session,
		events: SessionEvent[],
		baseProfile: LearningProfileStore,
	): Promise<ProfilePatch> {
		const studentMessageEvents    = events.filter(event => event.eventType === "message" && event.role === "student");
		const assistantMessageEvents  = events.filter(event => event.eventType === "message" && event.role === "assistant");

		// Determine how many assistant responses confirmed a correct answer
		const confirmedCorrectCount = assistantMessageEvents.filter(event =>
			CORRECT_CONFIRMATION_KEYWORDS.some(keyword =>
				event.content?.toLowerCase().includes(keyword),
			),
		).length;

		const totalAssistantExchanges = Math.max(1, assistantMessageEvents.length);
		const sessionSuccessRatio     = confirmedCorrectCount / totalAssistantExchanges;

		const operations: PatchOperation[] = [];

		// Generate a mastery update operation for each tracked skill
		for (const [skillId] of Object.entries(baseProfile.cognitive.skills)) {
			// Delta is proportional to how far the success ratio deviated from 0.5
			// (0.5 is neutral — no update; >0.5 gains mastery; <0.5 loses mastery)
			const masteryDelta = (sessionSuccessRatio - 0.5) * MASTERY_DELTA_SCALE_FACTOR;

			if (Math.abs(masteryDelta) > MINIMUM_MASTERY_DELTA_THRESHOLD) {
				operations.push({
					op:           "update_mastery",
					skillId,
					masteryDelta,
					confidence:   FINALIZER_OPERATION_CONFIDENCE,
					reason:       `Session success ratio: ${sessionSuccessRatio.toFixed(2)} ` +
					              `(${confirmedCorrectCount} confirmed correct / ${totalAssistantExchanges} exchanges)`,
					evidenceRefs: studentMessageEvents
						.slice(0, MAX_EVIDENCE_REFS_PER_OPERATION)
						.map(event => event.id),
				});
			}
		}

		const sessionSummary =
			`Session ${session.sessionId}: ` +
			`${studentMessageEvents.length} student turns, ` +
			`${confirmedCorrectCount} confirmed correct ` +
			`(success ratio ${sessionSuccessRatio.toFixed(2)}).`;

		return new ProfilePatch({
			id:                   crypto.randomUUID(),
			sessionId:            session.sessionId,
			studentId:            session.studentId,
			baseProfileVersion:   baseProfile.profileVersion,
			newProfileVersion:    baseProfile.profileVersion + 1,
			sessionSummary,
			operations,
			generatorType:        "FinalizerService",
			generatorSchemaName:  "1.0.0",
		});
	}

	/**
	 * Atomically commit a patch into the canonical store: compare `patch.baseProfileVersion`
	 * against the store's current `profileVersion` and, on match, apply + bump the version;
	 * on mismatch (`ProfilePatch.hasConflict`), reject and surface for re-derivation/review.
	 */
	public async applyPatchCompareAndSwap(
		store: LearningProfileStore,
		patch: ProfilePatch,
	): Promise<{ applied: boolean; newProfileVersion: number }> {
		if (patch.hasConflict(store.profileVersion)) {
			// The canonical profile moved on while this patch was being prepared — reject
			return { applied: false, newProfileVersion: store.profileVersion };
		}

		store.applyPatch(patch);
		return { applied: true, newProfileVersion: patch.newProfileVersion };
	}
}
