/**
 * ProfilePatch — an end-of-session diff proposal against `LearningProfileStore`.
 * Generated by `FinalizerService.finalizeSessionToPatch` from session evidence, then applied
 * atomically (compare-and-swap on `profileVersion`) by `LearningProfileStore.applyPatch`.
 * Mirrors the `ProfilePatch` Prisma model columns 1:1 in camelCase.
 */

/** A single proposed mutation against the canonical learning profile. */
export interface PatchOperation {
	op: string;
	skillId?: string;
	masteryDelta?: number;
	confidence: number;
	reason?: string;
	evidenceRefs: string[];
	pattern?: string;
	status?: string;
	path?: string;
	value?: unknown;
}

export class ProfilePatch {
	private _id: string;
	private _sessionId: string;
	private _studentId: string;
	private _baseProfileVersion: number;
	private _newProfileVersion: number;
	private _createdAt: Date;
	private _sessionSummary: string;
	private _operations: PatchOperation[];
	private _reviewFlags: Record<string, unknown> | null;
	private _generatorType: string | null;
	private _generatorSchemaName: string | null;

	constructor(data: {
		id: string;
		sessionId: string;
		studentId: string;
		baseProfileVersion: number;
		newProfileVersion: number;
		createdAt?: Date;
		sessionSummary: string;
		operations: PatchOperation[];
		reviewFlags?: Record<string, unknown> | null;
		generatorType?: string | null;
		generatorSchemaName?: string | null;
	}) {
		this._id = data.id;
		this._sessionId = data.sessionId;
		this._studentId = data.studentId;
		this._baseProfileVersion = data.baseProfileVersion;
		this._newProfileVersion = data.newProfileVersion;
		this._createdAt = data.createdAt ?? new Date();
		this._sessionSummary = data.sessionSummary;
		this._operations = data.operations;
		this._reviewFlags = data.reviewFlags ?? null;
		this._generatorType = data.generatorType ?? null;
		this._generatorSchemaName = data.generatorSchemaName ?? null;
	}

	get id(): string {
		return this._id;
	}
	get sessionId(): string {
		return this._sessionId;
	}
	get studentId(): string {
		return this._studentId;
	}
	get baseProfileVersion(): number {
		return this._baseProfileVersion;
	}
	get newProfileVersion(): number {
		return this._newProfileVersion;
	}
	get createdAt(): Date {
		return this._createdAt;
	}
	get sessionSummary(): string {
		return this._sessionSummary;
	}
	get operations(): PatchOperation[] {
		return this._operations;
	}
	get reviewFlags(): Record<string, unknown> | null {
		return this._reviewFlags;
	}
	get generatorType(): string | null {
		return this._generatorType;
	}
	get generatorSchemaName(): string | null {
		return this._generatorSchemaName;
	}

	public addOperation(op: PatchOperation): void {
		this._operations.push(op);
	}

	/** True when the canonical profile has moved on since this patch was generated (stale base). */
	public hasConflict(currentVersion: number): boolean {
		return this._baseProfileVersion !== currentVersion;
	}
}
